# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release
on:
  release

permissions:
  contents: write
  pages: write

jobs:
  build-demo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get release name
        run: |
          echo "pkg_name=${GITHUB_REF_NAME##*@}" >> "$GITHUB_ENV"
          echo "pkg_version=${GITHUB_REF_NAME%@*}" >> "$GITHUB_ENV"

      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: '.nvmrc'

      - name: NPM clean install
        run: npm ci

      - name: Compile packages bundle
        run: >-
          node ./build/bundle.js

      - name: Save bundle
        run: >-
          git stash save "rebundled for $pkg_name@$pkg_version"

      - name: Switch to GH Pages branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: gh-pages

      - name: Commit re-bundled packages
        run: |
          rm -rf ./docs/bundle/*
          git stash pop
          git add .
          git commit -m "release: rebuild for $pkg_name@$pkg_version"
